export const menuCategories = [
  { id: "appetizers", name: "Appetizers" },
  { id: "soups", name: "Soups" },
  { id: "curries", name: "Curries" },
  { id: "stir-fry", name: "Stir-Fry" },
  { id: "noodles", name: "Noodles & Rice" },
  { id: "desserts", name: "Desserts" },
  { id: "drinks", name: "Drinks" },
];

export const menuItems = [
  {
    id: 1,
    name: "Pad Thai",
    slug: "pad-thai",
    description:
      "Thailand's famous stir-fried rice noodle dish with eggs, tofu, bean sprouts, and peanuts in a sweet and savory sauce.",
    price: 16.9,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "noodles",
    ingredients: [
      "Rice noodles",
      "Eggs",
      "Tofu",
      "Bean sprouts",
      "Green onions",
      "Crushed peanuts",
      "Lime",
      "Tamarind sauce",
    ],
    allergens: ["Peanuts", "Eggs", "Soy"],
    spiceLevel: 1,
    isHot: true,
  },
  {
    id: 2,
    name: "Green Curry",
    slug: "green-curry",
    description:
      "A fragrant curry made with green curry paste, coconut milk, bamboo shoots, eggplant, and Thai basil.",
    price: 18.9,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "curries",
    ingredients: [
      "Green curry paste",
      "Coconut milk",
      "Bamboo shoots",
      "Eggplant",
      "Bell peppers",
      "Thai basil",
      "Kaffir lime leaves",
      "Fish sauce",
    ],
    allergens: ["Fish", "Coconut"],
    spiceLevel: 4,
    isHot: true,
  },
  {
    id: 3,
    name: "Tom Yum Goong",
    slug: "tom-yum-goong",
    description:
      "Hot and sour shrimp soup flavored with lemongrass, lime leaves, galangal, and chili.",
    price: 14.9,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "soups",
    ingredients: [
      "Shrimp",
      "Lemongrass",
      "Kaffir lime leaves",
      "Galangal",
      "Mushrooms",
      "Chili",
      "Lime juice",
      "Fish sauce",
    ],
    allergens: ["Shellfish", "Fish"],
    spiceLevel: 5,
    isHot: true,
  },
  {
    id: 4,
    name: "Spring Rolls",
    slug: "spring-rolls",
    description:
      "Crispy fried spring rolls filled with vegetables, glass noodles, and served with sweet chili sauce.",
    price: 9.9,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "appetizers",
    ingredients: [
      "Spring roll wrappers",
      "Glass noodles",
      "Cabbage",
      "Carrots",
      "Mushrooms",
      "Garlic",
      "Sweet chili sauce",
    ],
    allergens: ["Gluten"],
    spiceLevel: 0,
    isHot: false,
  },
  {
    id: 5,
    name: "Mango Sticky Rice",
    slug: "mango-sticky-rice",
    description:
      "Sweet sticky rice topped with fresh mango slices and coconut cream.",
    price: 10.9,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "desserts",
    ingredients: [
      "Glutinous rice",
      "Coconut milk",
      "Fresh mango",
      "Palm sugar",
      "Sesame seeds",
    ],
    allergens: ["Coconut"],
    spiceLevel: 0,
    isHot: false,
  },
  {
    id: 6,
    name: "Massaman Curry",
    slug: "massaman-curry",
    description:
      "A rich, relatively mild Thai curry with Muslim influences, containing potatoes, onions, peanuts, and meat.",
    price: 19.9,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "curries",
    ingredients: [
      "Massaman curry paste",
      "Coconut milk",
      "Potatoes",
      "Onions",
      "Peanuts",
      "Tamarind paste",
      "Cinnamon",
      "Cardamom",
    ],
    allergens: ["Peanuts", "Coconut"],
    spiceLevel: 2,
    isHot: false,
  },
  {
    id: 7,
    name: "Papaya Salad",
    slug: "papaya-salad",
    description:
      "Spicy salad made from shredded unripe papaya, tomatoes, chili, lime, and fish sauce.",
    price: 13.9,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "appetizers",
    ingredients: [
      "Green papaya",
      "Tomatoes",
      "Green beans",
      "Chili",
      "Garlic",
      "Lime",
      "Fish sauce",
      "Palm sugar",
      "Peanuts",
    ],
    allergens: ["Fish", "Peanuts"],
    spiceLevel: 5,
    isHot: true,
  },
  {
    id: 8,
    name: "Basil Chicken",
    slug: "basil-chicken",
    description:
      "Stir-fried minced chicken with Thai basil, chili, and garlic, served over rice.",
    price: 17.9,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "stir-fry",
    ingredients: [
      "Minced chicken",
      "Thai basil",
      "Chili",
      "Garlic",
      "Oyster sauce",
      "Fish sauce",
      "Jasmine rice",
    ],
    allergens: ["Fish"],
    spiceLevel: 3,
    isHot: true,
  },
  {
    id: 9,
    name: "Thai Iced Tea",
    slug: "thai-iced-tea",
    description: "Sweet and creamy Thai tea served over ice.",
    price: 5.9,
    image: "/placeholder.svg?height=600&width=600",
    categoryId: "drinks",
    ingredients: ["Thai tea mix", "Condensed milk", "Sugar", "Ice"],
    allergens: ["Dairy"],
    spiceLevel: 0,
    isHot: false,
  },
];

export const hotItems = menuItems.filter((item) => item.isHot);
